language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '8'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - name: test and lint
  - name: deploy
    if: branch = master AND type != pull_request
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
jobs:
  include:
    - stage: test and lint
      script:
        - time yarn run check
        - time yarn run test
    - stage: test and lint
      script:
        - time yarn integration-all
      if: branch = master AND type != pull_request
    - stage: deploy
      script:
        - yarn build
      deploy:
        provider: script
        script:
          - yarn run release
        skip_cleanup: true
        on:
          branch:
            - master
